version: 0.2

phases:
  install:
    commands:
      - echo 'Hello World (INSTALL phase)'
  pre_build:
    commands:
      - echo 'Hello World (PRE_BUILD phase)'
  build:
    commands:
      - echo 'Hello World (BUILD phase)'
  post_build:
    commands:
      - echo 'Hello World (POST_BUILD phase)'
artifacts:
  files:
    - appspec.yml
    - simple-pod.yaml
    - scripts/kube-apply
  base-directory: $CODEBUILD_SRC_DIR
  name: eks-apply-artifacts
  descard-paths: no